### ISSUE TITLE
Impossibile installare il componente

### ISSUE THREAD

**Issue by darpet75** [bigmoby/hassio-repository-addon#1]
Ciao, ho una installazione appena fatta di HASSOS su un Pi4 a 64bit.

Dal Supervisor aggiungo il tuo repository e poi tento di installare l'add-on ma mi da errore.

Impossibile installare il componente aggiuntivo
Can't install bigmoby/aarch64-addon-wireguard-client:0.1.8: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.1.8&fromImage=bigmoby%2Faarch64-addon-wireguard-client: Not Found ("manifest for bigmoby/aarch64-addon-wireguard-client:0.1.8 not found: manifest unknown: manifest unknown")

Help me please.
Grazie mille.
D.

**Comment by bigmoby** [comment]
Hi @darpet75 yes I'm on that issue. This morning I merged a PR in order to fix an open bug in API exposed port and in the evening I'll release the new version (v0.1.8) currently not published in Docker Hub. Please wait asap I'll publish it! 🙏

**Comment by bigmoby** [comment]
@darpet75 v0.1.8 has been released! Enjoy it! 🚀
